### ISSUE TITLE
Move theming to custom-properties

### ISSUE THREAD

**Issue by tomheller** [Dynatrace/css-groundhog#210]
Instead of moving styling to mixins and duplicating a lot of code, we could move the theming to css-custom-properties: 

```scss
@mixin unorderdlisttheme($color) {

  .list li:before {
    background-color: $color;
  }
}

.theme--blue {

  @include unorderdlisttheme($blue-600);
}

.theme--turquoise {

  @include unorderdlisttheme($turquoise-500);
}

.theme--purple {

  @include unorderdlisttheme($purple-600);
}

.theme--royalblue {

  @include unorderdlisttheme($royalblue-500);
}

.theme--green {

  @include unorderdlisttheme($green-500);
}
```

could fall back to turquoise and be done with:

```scss 
// define the theme colors once
.theme--blue {
--themecolor: $blue-500;
// e.v. lighter and darker 
}
.list li:before {
  background-color: $turquoise-500;
  background-color: var(--themecolor);
}
