### ISSUE TITLE
Button hover styles don't work in Key visuals

### ISSUE THREAD

**Issue by ddprrt** [Dynatrace/css-groundhog#35]
![screen shot 2016-09-05 at 11 49 43](https://cloud.githubusercontent.com/assets/1374451/18244160/d843d9b4-735e-11e6-9673-00304d6ba77e.png)

**Comment by ddprrt** [comment]
I guess this is a general problem (💂🏻 General Problem!) with hover styles on dark backgrounds. Let's think this through

![](https://media.giphy.com/media/777Aby0ZetYE8/giphy.gif)

**Comment by tomheller** [comment]
here is how we worked around this on the dynatrace.com website (http://github.dynatrace.vmta/dynatrace/dynatrace.com/blob/master/src/_sass/themes/_button.scss)

Code is within a mixin, getting the following parameters depending on theme color: 
* `$color` - theme color (500)
* `$hover` - darker theme color for hover (700)
* `$active` - even darker theme color for active (800) 
```scss
.theme--* {
  .section--bg .btn--primary {
    color: $color;
  }

  .section--bg .btn--primary:hover {
    color: $hover;
  }

  .section--bg .btn--primary:active {
    color: $active;
  }

  .btn--secondary {
    color: $color;
    border-color: $color;
  }

  .btn--secondary:hover {
    border-color: transparentize($color, 0.5);
    background-color: transparentize(#fff, 0.92);
  }

  .btn--secondary:active {
    border-color: transparentize($active, 0.5);
  }
}
```
